#!/bin/bash
if [ ! -d ./vendor ]
then
    composer install
fi
if [ -f .env ]
then
    php artisan key:generate
    read -p 'Database name: ' database
    sed -i "s/^DB_DATABASE=.*/DB_DATABASE=${database}/" .env
else
    cp .env.example .env && php artisan key:generate
    read -p 'Database name: ' database
    sed -i "s/^DB_DATABASE=.*/DB_DATABASE=${database}/" .env
fi
php artisan migrate:fresh --seed && php artisan passport:install --force
